version: '3'

services:
  postgres:
    image: 'postgres'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:4.0.10'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'
  
  app:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: bash start.sh
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
      - 'gems:/gems'

volumes:
  postgres:
  redis:
  gems: